name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]

jobs:
  # JOB 1: เทรนโมเดลบนเครื่อง IKP-4090 (Self-hosted)
  train-and-eval:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install System Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libopenblas-dev liblapack-dev gfortran

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install "numpy>=1.23.5" "scipy>=1.10.1" 
          pip install -r requirements.txt
          pip install evidently

      - name: Install DVC
        run: pip install dvc dvc-s3  

      - name: DVC Pull Data
        run: |
          dvc remote modify myminio endpointurl ${{ secrets.MINIO_ENDPOINT }}
          dvc remote modify myminio ssl_verify false
          dvc pull -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}

      - name: Run ML Pipeline
        run: |
          mkdir -p data
          touch data/new_production_data.csv 
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python main.py
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MLFLOW_S3_IGNORE_TLS: "true"
          AWS_REGION: us-east-1

  # JOB 2: สร้าง Docker Image (รันบน GitHub Cloud ได้เลยเพื่อความเร็ว)
  build-and-push:
    needs: train-and-eval
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fraud-detection:latest

  # JOB 3: อัปเดต KServe (รันบน GitHub Cloud)
  deploy-to-kserve:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Update KServe InferenceService
        run: |
          echo "KServe is updating to the latest image from GHCR..."
          kubectl apply -f k8s/inference-service.yaml